Fix offer url types
Now that the Keystone and Nova modules are expected to be tuples
containing at most one element, we'll need to update the offer
outputs, avoiding the following error:

  Error: Inconsistent conditional result types

  on outputs.tf line 55, in output "cert-distributor-offer-url":
  55:   value       = can(coalesce(var.external-cert-distributor-offer-url)) ? var.external-cert-distributor-offer-url : one(module.keystone[*].cert-distributor-offer-url)
    ├────────────────
    │ module.keystone is tuple with 1 element
    │ var.external-cert-distributor-offer-url is null